export const MESSAGE_SAVE_REQUEST = 'MESSAGE_SAVE_REQUEST'
export const MESSAGE_SAVE_SUCCESS = 'MESSAGE_SAVE_SUCCESS'
export const MESSAGE_SAVE_FAIL = 'MESSAGE_SAVE_FAIL'
export const MESSAGE_SAVE_RESET = 'MESSAGE_SAVE_RESET'


export const MESSAGE_LIST_REQUEST = 'MESSAGE_LIST_REQUEST'
export const MESSAGE_LIST_SUCCESS = 'MESSAGE_LIST_SUCCESS'
export const MESSAGE_LIST_RESET = 'MESSAGE_LIST_RESET'
export const MESSAGE_LIST_FAIL = 'MESSAGE_LIST_FAIL'